version: '3'
services:
  dolphinscheduler-zookeeper:
    image: zookeeper:latest
    container_name: zookeeper1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_4LW_COMMANDS_WHITELIST: srvr,ruok,wchs,cons
    volumes:
      - dolphinscheduler-zookeeper:/bitnami/zookeeper

  dolphinscheduler-postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=dolphinscheduler
    ports:
      - 5432:5432
    volumes:
      - dolphinscheduler-postgresql:/bitnami/postgresql

volumes:
  dolphinscheduler-postgresql:
  dolphinscheduler-zookeeper: